import type { Language } from "./i18n";

type ExploreLabels = {
  showOn: string; catalogs: string; search: string; loading: string; indexing: string;
  retry: string; empty: string; imported: string; importTitle: string;
  games: string; gamesOnPage: string; page: string; pageOf: string;
  previous: string; next: string; popularity: string; rating: string; preferenceFailed: string;
};

export const exploreLabels: Record<Language, ExploreLabels> = {
  en: { showOn: "Show on {site}", catalogs: "Game catalogues", search: "Search Flash games", loading: "Loading games...", indexing: "Loading Flash games... The first load may take several minutes while Y8 listings are indexed.", retry: "Retry", empty: "No Flash games found.", imported: "Imported", importTitle: "Import {title}", games: "{count} games", gamesOnPage: "{count} games on this page", page: "Page {page}", pageOf: "Page {page} of {total}", previous: "Previous page", next: "Next page", popularity: "Popularity", rating: "Rating", preferenceFailed: "Could not save the category setting." },
  zh: { showOn: "在 {site} 上查看", catalogs: "游戏目录", search: "搜索 Flash 游戏", loading: "正在加载游戏...", indexing: "正在加载 Flash 游戏... 首次建立 Y8 游戏索引可能需要几分钟。", retry: "重试", empty: "未找到 Flash 游戏。", imported: "已导入", importTitle: "导入 {title}", games: "{count} 个游戏", gamesOnPage: "本页 {count} 个游戏", page: "第 {page} 页", pageOf: "第 {page} 页，共 {total} 页", previous: "上一页", next: "下一页", popularity: "热度", rating: "评分", preferenceFailed: "无法保存类别设置。" },
  es: { showOn: "Ver en {site}", catalogs: "Catálogos de juegos", search: "Buscar juegos Flash", loading: "Cargando juegos...", indexing: "Cargando juegos Flash... La primera carga puede tardar varios minutos mientras se indexa Y8.", retry: "Reintentar", empty: "No se encontraron juegos Flash.", imported: "Importado", importTitle: "Importar {title}", games: "{count} juegos", gamesOnPage: "{count} juegos en esta página", page: "Página {page}", pageOf: "Página {page} de {total}", previous: "Página anterior", next: "Página siguiente", popularity: "Popularidad", rating: "Valoración", preferenceFailed: "No se pudo guardar el ajuste de la categoría." },
  fr: { showOn: "Voir sur {site}", catalogs: "Catalogues de jeux", search: "Rechercher des jeux Flash", loading: "Chargement des jeux...", indexing: "Chargement des jeux Flash... Le premier chargement peut prendre plusieurs minutes pendant l’indexation de Y8.", retry: "Réessayer", empty: "Aucun jeu Flash trouvé.", imported: "Importé", importTitle: "Importer {title}", games: "{count} jeux", gamesOnPage: "{count} jeux sur cette page", page: "Page {page}", pageOf: "Page {page} sur {total}", previous: "Page précédente", next: "Page suivante", popularity: "Popularité", rating: "Note", preferenceFailed: "Impossible d’enregistrer le réglage de la catégorie." },
  de: { showOn: "Auf {site} ansehen", catalogs: "Spielekataloge", search: "Flash-Spiele suchen", loading: "Spiele werden geladen...", indexing: "Flash-Spiele werden geladen... Die erste Indizierung von Y8 kann mehrere Minuten dauern.", retry: "Erneut versuchen", empty: "Keine Flash-Spiele gefunden.", imported: "Importiert", importTitle: "{title} importieren", games: "{count} Spiele", gamesOnPage: "{count} Spiele auf dieser Seite", page: "Seite {page}", pageOf: "Seite {page} von {total}", previous: "Vorherige Seite", next: "Nächste Seite", popularity: "Beliebtheit", rating: "Bewertung", preferenceFailed: "Die Kategorieeinstellung konnte nicht gespeichert werden." },
  "pt-BR": { showOn: "Ver no {site}", catalogs: "Catálogos de jogos", search: "Pesquisar jogos Flash", loading: "Carregando jogos...", indexing: "Carregando jogos Flash... A primeira carga pode levar vários minutos durante a indexação do Y8.", retry: "Tentar novamente", empty: "Nenhum jogo Flash encontrado.", imported: "Importado", importTitle: "Importar {title}", games: "{count} jogos", gamesOnPage: "{count} jogos nesta página", page: "Página {page}", pageOf: "Página {page} de {total}", previous: "Página anterior", next: "Próxima página", popularity: "Popularidade", rating: "Avaliação", preferenceFailed: "Não foi possível salvar a configuração da categoria." },
  ja: { showOn: "{site} で見る", catalogs: "ゲームカタログ", search: "Flash ゲームを検索", loading: "ゲームを読み込み中...", indexing: "Flash ゲームを読み込み中... Y8 の初回インデックス作成には数分かかる場合があります。", retry: "再試行", empty: "Flash ゲームが見つかりません。", imported: "インポート済み", importTitle: "{title} をインポート", games: "{count} ゲーム", gamesOnPage: "このページに {count} ゲーム", page: "{page} ページ", pageOf: "{total} ページ中 {page} ページ", previous: "前のページ", next: "次のページ", popularity: "人気", rating: "評価", preferenceFailed: "カテゴリ設定を保存できませんでした。" },
  ko: { showOn: "{site}에서 보기", catalogs: "게임 카탈로그", search: "Flash 게임 검색", loading: "게임 불러오는 중...", indexing: "Flash 게임 불러오는 중... Y8 목록을 색인하는 첫 로딩에는 몇 분이 걸릴 수 있습니다.", retry: "다시 시도", empty: "Flash 게임을 찾을 수 없습니다.", imported: "가져옴", importTitle: "{title} 가져오기", games: "게임 {count}개", gamesOnPage: "이 페이지의 게임 {count}개", page: "{page}페이지", pageOf: "{total}페이지 중 {page}페이지", previous: "이전 페이지", next: "다음 페이지", popularity: "인기도", rating: "평점", preferenceFailed: "카테고리 설정을 저장할 수 없습니다." },
  hi: { showOn: "{site} पर देखें", catalogs: "गेम कैटलॉग", search: "Flash गेम खोजें", loading: "गेम लोड हो रहे हैं...", indexing: "Flash गेम लोड हो रहे हैं... Y8 की सूची बनाने में पहली बार कई मिनट लग सकते हैं।", retry: "फिर कोशिश करें", empty: "कोई Flash गेम नहीं मिला।", imported: "आयात किया गया", importTitle: "{title} आयात करें", games: "{count} गेम", gamesOnPage: "इस पृष्ठ पर {count} गेम", page: "पृष्ठ {page}", pageOf: "{total} में से पृष्ठ {page}", previous: "पिछला पृष्ठ", next: "अगला पृष्ठ", popularity: "लोकप्रियता", rating: "रेटिंग", preferenceFailed: "श्रेणी की सेटिंग सहेजी नहीं जा सकी।" },
  ar: { showOn: "عرض على {site}", catalogs: "كتالوجات الألعاب", search: "البحث عن ألعاب Flash", loading: "جارٍ تحميل الألعاب...", indexing: "جارٍ تحميل ألعاب Flash... قد يستغرق التحميل الأول عدة دقائق لفهرسة قوائم Y8.", retry: "إعادة المحاولة", empty: "لم يتم العثور على ألعاب Flash.", imported: "تم الاستيراد", importTitle: "استيراد {title}", games: "{count} ألعاب", gamesOnPage: "{count} ألعاب في هذه الصفحة", page: "الصفحة {page}", pageOf: "الصفحة {page} من {total}", previous: "الصفحة السابقة", next: "الصفحة التالية", popularity: "الشعبية", rating: "التقييم", preferenceFailed: "تعذر حفظ إعداد الفئة." },
  ru: { showOn: "Посмотреть на {site}", catalogs: "Каталоги игр", search: "Поиск Flash-игр", loading: "Загрузка игр...", indexing: "Загрузка Flash-игр... Первая индексация каталога Y8 может занять несколько минут.", retry: "Повторить", empty: "Flash-игры не найдены.", imported: "Импортировано", importTitle: "Импортировать {title}", games: "Игр: {count}", gamesOnPage: "Игр на этой странице: {count}", page: "Страница {page}", pageOf: "Страница {page} из {total}", previous: "Предыдущая страница", next: "Следующая страница", popularity: "Популярность", rating: "Оценка", preferenceFailed: "Не удалось сохранить настройку категории." },
};
